require("config.lsp")
require("config.lsptool")
require("config.diagnostic")
require("config.folding")
require("config.langIndent")
require("config.pack")
require("config.tabline")
require("config.statusline")
