mode = "stack"
vcs = "git"
watch = false
exclude_untracked = false
line_numbers = true
tab_width = 4
file_gap = 1
hunk_gap = 0
wrap_lines = true
hunk_headers = false
menu_bar = false
agent_notes = false
animations = true
sidebar = false
transparent_background = true
theme = "gruvbox-dark-hard"
copy_decorations = false
cursor_line = "row"
