# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  expandFocusedSidePanel: true
  showNumstatInFilesView: true
  nerdFontsVersion: "3"
  mouseEvents: false
  branchColorPatterns:
    "^feature/": cyan
    "^fix/": red
    "^chore/": yellow
    "^release/": green
    "^main$": "#ffffff"
    "^master$": "#ffffff"
  theme:
    activeBorderColor:
      - cyan
      - bold
    inactiveBorderColor:
      - default
    selectedLineBgColor:
      - blue
    unstagedChangesColor:
      - red
git:
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=format:'%C(yellow)%h%Creset %C(bold blue)%an%Creset %C(green)(%ar)%Creset %s %C(auto)%d%Creset' {{branchName}} --"
os:
  editPreset: "nvim"
customCommands:
  - key: "C"
    command: "git commit -m '{{.Form.Type}}: {{.Form.Message}}'"
    context: "files"
    description: "Conventional commit"
    prompts:
      - type: "menu"
        key: "Type"
        title: "Commit type:"
        options:
          - name: "feat"
            value: "feat"
          - name: "fix"
            value: "fix"
          - name: "docs"
            value: "docs"
          - name: "test"
            value: "test"
          - name: "style"
            value: "style"
          - name: "chore"
            value: "chore"
          - name: "refactor"
            value: "refactor"
      - type: "input"
        key: "Message"
        title: "Message:"
