#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# window
yabai -m config window_origin_display           default 
yabai -m config window_placement                second_child
yabai -m config window_topmost                  off
yabai -m config window_shadow                   off
yabai -m config window_opacity                  off
yabai -m config active_window_opacity           1.0
yabai -m config normal_window_opacity           0.90
yabai -m config window_border                   off
yabai -m config window_border_width             6
yabai -m config active_window_border_color      0xff775759
yabai -m config normal_window_border_color      0xff555555
yabai -m config insert_feedback_color           0xffd75f5f
yabai -m config auto_balance                    off
yabai -m config split_ratio                     0.50


# layout (bsp,stack or float) & paddding
yabai -m config layout          bsp
yabai -m config top_padding     00
yabai -m config bottom_padding  00
yabai -m config left_padding    00
yabai -m config right_padding   00
yabai -m config window_gap      05

# mouse
yabai -m config focus_follows_mouse     off
yabai -m config mouse_follows_focus     off
yabai -m config mouse_modifier          alt
yabai -m config mouse_action1           move
yabai -m config mouse_action2           resize
yabai -m config mouse_drop_action       swap

# disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Finder$" manage=off 
yabai -m rule --add app="^App Store$" manage=off 
yabai -m rule --add app="^Safari$" manage=off 
yabai -m rule --add app="^同花顺$" manage=off 
yabai -m rule --add app="^NetEaseMusic$" manage=off 
yabai -m rule --add app="^Foxmail$" manage=off 
yabai -m rule --add app="^WeChat$" manage=off 
yabai -m rule --add app="^Steam$" manage=off 

echo "yabai configuration loaded.."
